/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/rpnstring_test.check" instead.
 */

#include <check.h>

#line 1 "tests/rpnstring_test.check"
#include "../defs.h"
#include "../util.h"

START_TEST(parenthesis_ok_test)
{
#line 5
   ck_assert_int_eq(parenthesis_ok("()"), OK);
   ck_assert_int_eq(parenthesis_ok("(()"), NOK);
   ck_assert_int_eq(parenthesis_ok("((a+b)*(c+d))"), OK);
   ck_assert_int_eq(parenthesis_ok("((a+b)*(c+d)))"), NOK);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, parenthesis_ok_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
