/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/rpnstring_test.check" instead.
 */

#include <check.h>

#line 1 "tests/rpnstring_test.check"
#include "../defs.h"
#include "../rpntools.h"

START_TEST(checkMatchingParenthesis_test)
{
#line 5
   ck_assert_int_eq(checkMatchingParenthesis("()"), OK);
   ck_assert_int_eq(checkMatchingParenthesis("(()"), NOK);
   ck_assert_int_eq(checkMatchingParenthesis("((a+b)*(c+d))"), OK);
   ck_assert_int_eq(checkMatchingParenthesis("((a+b)*(c+d)))"), NOK);
   ck_assert_int_eq(checkMatchingParenthesis("((a+b)"), NOK);
   ck_assert_int_eq(checkMatchingParenthesis("(((a+b)*(c+d))))"), NOK);
   ck_assert_int_eq(checkMatchingParenthesis(")("), NOK);
   ck_assert_int_eq(checkMatchingParenthesis("))"), NOK);

}
END_TEST

START_TEST(isLowerCaseLetter_test)
{
#line 15
   ck_assert_int_eq(isLowerCaseLetter('A'), NOK);
   ck_assert_int_eq(isLowerCaseLetter('a'), OK);
   ck_assert_int_eq(isLowerCaseLetter('$'), NOK);

}
END_TEST

START_TEST(isAllowedOperator_test)
{
#line 20
   ck_assert_int_eq(isAllowedOperator('+'), OK);
   ck_assert_int_eq(isAllowedOperator('/'), OK);
   ck_assert_int_eq(isAllowedOperator('-'), OK);
   ck_assert_int_eq(isAllowedOperator('*'), OK);
   ck_assert_int_eq(isAllowedOperator('^'), OK);
   ck_assert_int_eq(isAllowedOperator('@'), NOK);

}
END_TEST

START_TEST(infix_checkValidChars_test)
{
#line 28
   ck_assert_int_eq(checkValidChars("(a+b)", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("a+b+3", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("$$a+b+3", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("(a+b ) ", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("3+3", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("A+B", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("FOO_*", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("+3", INFIX_RULES), VALID_CHARPOS);

}
END_TEST

START_TEST(rpn_checkValidChars_test)
{
#line 38
   ck_assert_int_eq(checkValidChars("ab+", RPN_RULES), VALID_CHARPOS);
   ck_assert_int_eq(checkValidChars("abc*^", RPN_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("(a+b)", RPN_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars(" ab++ ", RPN_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("(A+B)", RPN_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("*AB", RPN_RULES), VALID_CHARPOS);

}
END_TEST

START_TEST(checkSanity_test)
{
#line 46
   ck_assert_int_eq(checkSanity("(a+b)*(a^c)", INFIX_RULES), OK);
   ck_assert_int_eq(checkSanity(")a-b(", INFIX_RULES), NOK);
   ck_assert_int_eq(checkSanity("ab+", RPN_RULES), OK);

}
END_TEST

START_TEST(ERROR_FLAGS_test)
{
#line 51
   setErrorFlag(ERR_PARENTHESIS_UNBALANCED);
   ck_assert_int_eq(getErrorFlag(ERR_PARENTHESIS_UNBALANCED), TRUE);
   ck_assert_int_eq(getErrorFlag(ERR_INVALID_CHARACTER), FALSE);
   setErrorFlag(ERR_INVALID_CHARACTER);
   ck_assert_int_eq(getErrorFlag(ERR_PARENTHESIS_UNBALANCED), TRUE);
   ck_assert_int_eq(getErrorFlag(ERR_INVALID_CHARACTER), TRUE);

}
END_TEST

START_TEST(RPNtoInfix_test)
{
#line 59
   ck_assert_str_eq(RPNtoInfix("ab+"), "(a+b)");
   ck_assert_str_eq(RPNtoInfix("ag+ba-c+cedf^*+^*"), "((a+g)*(((b-a)+c)^(c+(e*(d^f)))))");
   ck_assert_str_eq(RPNtoInfix("ab+c*d^"), "(((a+b)*c)^d)");
   ck_assert_str_eq(RPNtoInfix("a+b"), "");
   ck_assert_int_eq(getErrorFlag(ERR_UNBALANCED_EXPRESSION), TRUE);
   ck_assert_str_eq(RPNtoInfix("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa+"), "");
   ck_assert_int_eq(getErrorFlag(ERR_STACK_OVERFLOW), TRUE);
   ck_assert_str_eq(RPNtoInfix("+ab"), "");
   ck_assert_int_eq(getErrorFlag(ERR_UNBALANCED_EXPRESSION), TRUE);
   ck_assert_str_eq(RPNtoInfix("a++"), "");
   ck_assert_int_eq(getErrorFlag(ERR_UNBALANCED_EXPRESSION), TRUE);
   ck_assert_str_eq(RPNtoInfix("++"), "");
   ck_assert_int_eq(getErrorFlag(ERR_UNBALANCED_EXPRESSION), TRUE);

}
END_TEST

START_TEST(getRPN_test)
{
#line 74

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, checkMatchingParenthesis_test);
    tcase_add_test(tc1_1, isLowerCaseLetter_test);
    tcase_add_test(tc1_1, isAllowedOperator_test);
    tcase_add_test(tc1_1, infix_checkValidChars_test);
    tcase_add_test(tc1_1, rpn_checkValidChars_test);
    tcase_add_test(tc1_1, checkSanity_test);
    tcase_add_test(tc1_1, ERROR_FLAGS_test);
    tcase_add_test(tc1_1, RPNtoInfix_test);
    tcase_add_test(tc1_1, getRPN_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
