/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/rpnstring_test.check" instead.
 */

#include <check.h>

#line 1 "tests/rpnstring_test.check"
#include "../defs.h"
#include "../util.h"

START_TEST(checkMatchingParenthesis_test)
{
#line 5
   ck_assert_int_eq(checkMatchingParenthesis("()"), OK);
   ck_assert_int_eq(checkMatchingParenthesis("(()"), NOK);
   ck_assert_int_eq(checkMatchingParenthesis("((a+b)*(c+d))"), OK);
   ck_assert_int_eq(checkMatchingParenthesis("((a+b)*(c+d)))"), NOK);

}
END_TEST

START_TEST(isLowerCaseLetter_test)
{
#line 11
   ck_assert_int_eq(isLowerCaseLetter('A'), NOK);
   ck_assert_int_eq(isLowerCaseLetter('a'), OK);
   ck_assert_int_eq(isLowerCaseLetter('$'), NOK);

}
END_TEST

START_TEST(isAllowedOperator_test)
{
#line 16
   ck_assert_int_eq(isAllowedOperator('+'), OK);
   ck_assert_int_eq(isAllowedOperator('/'), OK);
   ck_assert_int_eq(isAllowedOperator('-'), OK);
   ck_assert_int_eq(isAllowedOperator('*'), OK);
   ck_assert_int_eq(isAllowedOperator('^'), OK);
   ck_assert_int_eq(isAllowedOperator('@'), NOK);


}
END_TEST

START_TEST(infix_checkValidChars_test)
{
#line 25
   ck_assert_int_eq(checkValidChars("(a+b)", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("a+b+3", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("$$a+b+3", INFIX_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("(a+b ) ", INFIX_RULES), VALID_CHARPOS);

}
END_TEST

START_TEST(rpn_checkValidChars_test)
{
#line 31
   ck_assert_int_eq(checkValidChars("ab+", RPN_RULES), VALID_CHARPOS);
   ck_assert_int_eq(checkValidChars("abc*^", RPN_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars("(a+b)", RPN_RULES), VALID_CHARPOS);
   ck_assert_int_ne(checkValidChars(" ab++ ", RPN_RULES), VALID_CHARPOS);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, checkMatchingParenthesis_test);
    tcase_add_test(tc1_1, isLowerCaseLetter_test);
    tcase_add_test(tc1_1, isAllowedOperator_test);
    tcase_add_test(tc1_1, infix_checkValidChars_test);
    tcase_add_test(tc1_1, rpn_checkValidChars_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
